(function($){
    $.URL = {
        "common":{
          "rootPath":"http://www.cseicms.com/"
        },
        "power":{
            "add":"rs/power/add",
            "update":"rs/power/update",
            "delete":"rs/power/delete",
            "list":"rs/power/list"
        },
        "user":{
            "add":"rs/user/add",
            "update":"rs/user/update",
            "delete":"rs/user/delete",
            "list":"rs/user/list",
            "getId":"rs/user/getIdByName" ,
            "currentUserId": "rs/user/currentUserId",
            "currentUserInfo":"rs/user/currentUser"
        },
        "authority":{
             "add":"rs/authority/add",
             "update":"rs/authority/update",
             "delete":"rs/authority/delete",
            "list":"rs/authority/list"
        },
        "userAuthority":{
              "add":"rs/userAuthority/add"
        },
        "device":{
            "add":"rs/device/add",
            "update":"rs/device/update",
            "delete":"rs/device/delete",
            "list":"rs/device/list",
            "getIdByNumber":"rs/device/getIdByNumber",
            "detailInfo":"rs/device/detailInfo",
            "findByCondition":"rs/device/findByCondition"
        },
        "deviceType":{
            "list":"rs/deviceType/list",
            "add":"rs/deviceType/add",
            "update":"rs/deviceType/update",
            "delete":"rs/deviceType/delete",
            "getIdByName":"rs/deviceType/getIdByName"
        },
        "dashboard":{
            "deviceList":"rs/device/list",
            "installationList":"rs/installation/findByCondition",
            "removeList":"rs/remove/findByCondition",
            "preBuryList":"rs/preBury/getPreburyList",
            "contractList":"rs/contract/getContractList",
            "inStockList":"rs/stock_in_sheet/getInStockList",
            "outStockList":"rs/stock_out_sheet/getOutStockList"
        },
        "deviceReport":{
            "deviceAccountReport":"rs/deviceReport/deviceAccountReport",
            "exportDeviceAccountReport":"rs/deviceReport/exportDeviceAccountReport",
            "rentDeviceReport":"rs/deviceReport/rentDeviceReport",
            "exportRentDeviceReport":"rs/deviceReport/exportRentDeviceReport",
            "deviceTrendReport":"rs/deviceReport/deviceTrendReport",
            "exportDeviceTrendReport":"rs/deviceReport/exportDeviceTrendReport"
        },
        "maintainRule":{
            "add":"rs/maintainRule/add",
            "update":"rs/maintainRule/update",
            "delete":"rs/maintainRule/delete",
            "list":"rs/maintainRule/list"
        },
        "deviceMaintain":{
            "add":"rs/deviceMaintain/add",
            "update":"rs/deviceMaintain/update",
            "delete":"rs/deviceMaintain/delete",
            "getLastDeviceMaintainByDeviceGroup":"rs/deviceMaintain/getLastDeviceMaintainByDeviceGroup"
        },
        "project":{
            "add":"rs/project/add",
            "update":"rs/project/update",
            "delete":"rs/project/delete",
            "list":"rs/project/list"
        },
        "projectUnit":{
            "add":"rs/projectUnit/add",
            "update":"rs/projectUnit/update",
            "delete":"rs/projectUnit/delete",
            "list":"rs/projectUnit/list"
        },
        "projectSegment":{
            "add":"rs/projectSegment/add",
            "update":"rs/projectSegment/update",
            "delete":"rs/projectSegment/delete",
            "list":"rs/projectSegment/list",
            "getListByProjectId":"rs/projectSegment/getListByProjectId"
        }
    }
})(jQuery);